
# #################### Default Setup ####################
# wandb: False
# seed: 0
# enable_benchmark: True
# use_amp: True
# multiprocessing: False
# main_gpu: '0'
# num_workers: 1
# pin_memory: False
# refactoring: True
# verbose: False
# # method_name: FedAvg
# remark: ""

# checkpoint_path: './checkpoints'
# exp_name: base
# output_model_path: 'res18.pt'
# save_freq: 1000
# batch_size: 2
# save_test: False 

# ## Resume
# load_model_path: False      # ====> may be like ./checkpoints/CIFAR100/iid/iid_base/res18.pt. use command line +load_model_path=(path)
# wandb_resume_id: False


# ###### wandb && logging ######
# project: "FedRCL"
# log_dir: './checkpoints' 


# #################### Data Split ####################
# split:
#   mode: 'dirichlet'
#   alpha: 0.3
#   class_per_client: 0 # only for skew mode
#   unbalanced: False
#   overlap_ratio: 0.0
#   create_client_dataset: False

# #################### Optimizer ####################
# optimizer:
#   name: sgd
#   momentum: 0.0
#   wd: 1e-3


# #################### Eval ####################
# eval:
#   freq: 1
#   batch_size: 2

# analysis: False

# defaults:
#   - _self_
#   - trainer: base
#   - client: base
#   - evaler: base
#   - dataset: cifar100
#   - server: base
#   - model: resnet18
#   - override hydra/job_logging: default
#   - override hydra/hydra_logging: default


#################### Default Setup ####################
wandb: False
seed: 0
enable_benchmark: True
use_amp: True
multiprocessing: False
main_gpu: '0'
num_workers: 4
pin_memory: True
refactoring: True
verbose: False
# method_name: FedAvg
remark: ""

checkpoint_path: './checkpoints'
exp_name: base
output_model_path: 'res18.pt'
save_freq: 1000
batch_size: 2
save_test: False 

## Resume
load_model_path: False      # ====> may be like ./checkpoints/CIFAR100/iid/iid_base/res18.pt. use command line +load_model_path=(path)
wandb_resume_id: False


###### wandb && logging ######
project: "FedRCL"
log_dir: './checkpoints' 


#################### Data Split ####################
split:
  mode: 'dirichlet'
  alpha: 0.3
  class_per_client: 0 # only for skew mode
  unbalanced: False
  overlap_ratio: 0.0
  create_client_dataset: False

#################### Optimizer ####################
optimizer:
  name: sgd
  momentum: 0.0
  wd: 1e-3


#################### Eval ####################
eval:
  freq: 1
  batch_size: 2

analysis: False


defaults:
  - _self_  #
  - trainer: base
  - client: base
  - evaler: base
  - dataset: cifar100  # Change dataset to the appropriate name here
  - server: base
  - model: resnet18


#################### Dataset Path ####################
dataset_paths:
  cifar10: "data/cifar-10-batches-py"
  cifar100: "data/cifar-100-python"
  tiny_imagenet: "data/tiny-imagenet-200"

trainer:
  epochs: 10

